name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy with SSH
        uses: appleboy/ssh-action@v0.1.7 # <-- Esta es la acción que manejará el SSH
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Los siguientes comandos se ejecutan en tu servidor EC2
            
            # 1. Detener la aplicación
            echo "Deteniendo la aplicación..."
            # Asegúrate de usar el comando correcto para tu aplicación (ej. pm2, systemd)
            sudo -u deployuser pm2 stop portafolio-backend || true

            # 2. Navegar al directorio de la aplicación y actualizar código
            echo "Actualizando código..."
            sudo -u deployuser git -C /home/deployuser/portafolio pull

            # 3. Instalar dependencias si es necesario
            # sudo -u deployuser npm install --prefix /home/deployuser/portafolio/frontend
            # sudo -u deployuser npm install --prefix /home/deployuser/portafolio/backend

            # 4. MIGRACIÓN DE LA BASE DE DATOS
            echo "Ejecutando migración de base de datos..."
            # sudo -u deployuser node /home/deployuser/portafolio/migrate.js

            # 5. Iniciar la aplicación de nuevo
            echo "Iniciando la aplicación..."
            sudo -u deployuser pm2 start portafolio-backend || true 
            
            echo "Despliegue completado."